### ISSUE TITLE
Issue with publishing

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-interpolate#1]
I followed the instructions on Pursuit, but ran into this issue when publishing.
```
$> pulp publish
Publishing purescript-interpolate at v1.0.0. Is this ok? [y/n] y
* About to execute:
> git push origin HEAD refs/tags/v1.0.0
Ok? [y/n] y
Counting objects: 2, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 323 bytes | 323.00 KiB/s, done.
Total 2 (delta 0), reused 0 (delta 0)
To github.com:JordanMartinez/purescript-interpolate.git
   7b6b7ee..c035679  HEAD -> master
 * [new tag]         v1.0.0 -> v1.0.0
* Registering your package on Bower...
* About to execute:
> bower register purescript-interpolate git://github.com/jordanmartinez/purescript-interpolate.git
Ok? [y/n] y
bower resolve       git://github.com/jordanmartinez/purescript-interpolate.git#*
bower download      https://github.com/jordanmartinez/purescript-interpolate/archive/v1.0.0.tar.gz
bower extract       purescript-interpolate#* archive.tar.gz
bower resolved      git://github.com/jordanmartinez/purescript-interpolate.git#1.0.0
? Registering a package will make it installable via the registry (https://registry.bower.io), continue? Yes
bower register      git://github.com/jordanmartinez/purescript-interpolate.git
bower EUNKNOWN      Unknown error: 500 - Registering bower package names is not supported anymore. You can install any bower package on github with command like "bower install jquery/jquery-dist --save"
* ERROR: Subcommand terminated with exit code 1
```

**Comment by JordanMartinez** [comment]
I'm out of time, so I'll have to get to this later.

**Comment by i-am-the-slime** [comment]
Personally, I wouldn't bother with this stuff and only support use `spago` and somehow make it into a package set.

**Comment by JordanMartinez** [comment]
`spago` won't allow you to add a package to the package set unless it's already published via bower. See [publish my library](https://github.com/spacchetti/spago/#publish-my-library)

Once published, I was going to add it to the package set.

**Comment by rnons** [comment]
I think you can answer `N` for the last question `Registering a package will make it installable via the registry` and pulp will continue publishing.

**Comment by paluh** [comment]
> Personally, I wouldn't bother with this stuff and only support use spago and somehow make it into a package set.

@i-am-the-slime I think tha bower versions of libraries are really essential to the whole ecosystem. It seems to me that it would be hard to consume this library from another one (imagine 'purescript-interpolate-formatters') without a registry with clear versioning model...

**Comment by JordanMartinez** [comment]
> I think you can answer N for the last question Registering a package will make it installable via the registry and pulp will continue publishing.

@rnons Thanks for the tip. I'll try doing that once #2 gets figured out.

**Comment by JordanMartinez** [comment]
I answered 'N' for the last question and `pulp publish` completed. Hoewver, this repo is still not installable via `bower i purescript-interpolate`:
```bash
$> bower i purescript-interpolate
bower ENOTFOUND     Package purescript-interpolate not found
```
This worked:

```bash
$> bower i jordanmartinez/purescript-interpolate
```
... but this didn't:
```bash
mkdir ps-i
cd pis-i/
pulp init
bower i jordanmartinez/purescript-interpolate
pulp repl

Error found:
in module Data.Interpolate
at bower_components/purescript-interpolate/src/Data/Interpolate.purs:28:1 - 28:40 (line 28, column 1 - line 28, column 40)

  Module Partial.Unsafe was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.


See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
or to contribute content related to this error.
```

**Comment by rnons** [comment]
You need to add `purescript-partial` to your [bower.json](https://github.com/JordanMartinez/purescript-interpolate/blob/master/bower.json#L18-L20)
```diff
  "dependencies": {
   "purescript-prelude": "^4.1.1",
+  "purescript-partial": "^2.0.1"
  },
```

**Comment by JordanMartinez** [comment]
I know, but thanks for stating that anyways in case I didn't.

I'd rather use FFI than depend on another library, so that the transitive dependencies of this library are small.

**Comment by JordanMartinez** [comment]
This project's ReadMe now explains how to install this library using either Bower or Spago.

Since this project can't be installed via `bower i purescript-interpolate`, I'm not sure how that will affect things when I try to get this added to the main Spago package set.

**Comment by rnons** [comment]
I think this doesn't affect spago, since package-sets always point to git url.

But it does affect a library depending on `purescript-interpolate`, the bower.json of such library will look like

```
  "dependencies": {
    "purescript-a": "^1.0.0",
    "purescript-b": "^2.0.0",    
    "purescript-interpolate": "jordanmartinez/purescript-interpolate#^2.0.1"
}
```

**Comment by JordanMartinez** [comment]
@rnons Good to know. I'll update the Readme of this project to note that.
