### ISSUE TITLE
Use purescript-partial?

### ISSUE THREAD

**Issue by JamieBallingall** [JordanMartinez/purescript-interpolate#6]
This library currently has a custom, Javascript-implemented, function called `unsafeCrashWith`. If we add a dependency to purescript-partial we could remove all the Javascript in this library and simply use the `unsafeCrashWith` provided by purescript-partial.

I'm happy to create a PR if that is a direction you want to go.

Thoughts?

**Comment by JordanMartinez** [comment]
Part of the reason why I am using custom JS here is so this library does not have any dependencies. However, I think `partial` is low enough that adding that as a dependency isn't a problem. So, yes, please make a PR.
